### ISSUE TITLE
Likelihoods organization for different TT, TE, EE, TTTEEE modes 

### ISSUE THREAD

**Issue by xgarrido** [simonsobs/LAT_MFLike#3]
So far the ```MFLike``` likelihood has been tested only for TTTEEE mode and the associated ```MFLike.yaml``` file is filled for this mode (all the nuisance parameters are set for instance). 

We can imagine to organize likelihoods for TT, TE, EE and TTTEEE in the same way as for Planck 2018 (https://github.com/CobayaSampler/cobaya/tree/master/cobaya/likelihoods/planck_2018_highl_plik) where each likelihoods just inherits from a base class that actually do the job. The current ```MFLike``` likelihood can play the same role but then we need to create independant likelihoods that inherits from it and we also need to define several yaml files with corresponding nuisance parameters (as well as corresponding proposal). Any thoughts ?

**Comment by mabitbol** [comment]
If possible could we write only a new yaml file for each new likelihood? Or are they so different that we cannot do this? The yaml would define the model including foregrounds etc. We would modify MFLike to be able to construct the appropriate model from the config file. If that’s overly complicated then I agree with your method where each new likelihood inherits from a base likelihood.



On Nov 11, 2019, at 17:04, Xavier Garrido <notifications@github.com<mailto:notifications@github.com>> wrote:


So far the MFLike likelihood has been tested only for TTTEEE mode and the associated MFLike.yaml file is filled for this mode (all the nuisance parameters are set for instance).

We can imagine to organize likelihoods for TT, TE, EE and TTTEEE in the same way as for Planck 2018 (https://github.com/CobayaSampler/cobaya/tree/master/cobaya/likelihoods/planck_2018_highl_plik) where each likelihoods just inherits from a base class that actually do the job. The current MFLike likelihood can play the same role but then we need to create independant likelihoods that inherits from it and we also need to define several yaml files with corresponding nuisance parameters (as well as corresponding proposal). Any thoughts ?

**Comment by cmbant** [comment]
At the moment Cobaya needs at least a new class for each likelihood, you can't reference .yaml files directly (but you can now define all the classes in one module rather than making lots of separate .py files). You can of course also override the relevant setting when you run as long as the number of nuisance parameters is the same. (Could also think about some automated way of generating a trivial wrapper class whenever a yaml is referenced directly with no matching class provided.)

Btw, if you inherit from [_InstallableLikelihood](https://cobaya.readthedocs.io/en/external_modules/cosmo_external_likelihood_class.html#installablelikelihood) or one of the descendants, and define the download location, it should support automatic data file installation via the standard Cobaya mechanism (though I haven't actually tested it with external likelihoods).

**Comment by cmbant** [comment]
Did anyone try this? Would be good to know if any changes are needed to underlying Cobaya structures (e.g. not clear how to dynamically vary the nuisance parameters because on requirements). What is ACT doing?

**Comment by cmbant** [comment]
My attempt https://github.com/simonsobs/LAT_MFLike/pull/89

**Comment by cmbant** [comment]
I guess can be closed after #90
