### ISSUE TITLE
About cl_cib_Choi2020.dat file

### ISSUE THREAD

**Issue by vivianmiranda** [simonsobs/LAT_MFLike#41]
Hi,

I hope you are all well and safe. I am trying to run a likelihood analysis with v0.7 and the likelihood keeps asking about cl_cib_Choi2020.dat file which I can't find anywhere (it is not part of fgspectra). Is this file public? If not, it is possible to run any SO analysis (with v0.7 sims)?

Best
Vivian

**Comment by xgarrido** [comment]
The current `v0.7` release relies on [this](https://github.com/simonsobs/fgspectra/tree/act_sz_x_cib) specific `fgspectra` branch (there is an on-going PR https://github.com/simonsobs/fgspectra/pull/39 but not sure it will be merged as it is). So the `cl_cib_Choi2020.dat` file is available [here](https://github.com/simonsobs/fgspectra/blob/50865f485ce37f128b58ac52a39a57d669038608/fgspectra/data/cl_cib_Choi2020.dat) but `LAT_MFLike` should take care of it by installing the `fgspectra` needed branch (see https://github.com/simonsobs/LAT_MFLike/blob/master/setup.py#L19) as well as `syslibrary`. 

As far as I remember, if you already have `fgspectra` installed, I'm not sure the associated files like `cl_cib_Choi2020.dat` are pulled into the `data` directory of `fgspectra`. So one way to solve this issue is to uninstall `fgspectra` and then rerun `pip install -e /where/lat_mflike/has/been/cloned`. Another way is to redo the installation process on a fresh `python` virtual environmenent.

**Comment by vivianmiranda** [comment]
it worked. Thanks
