### ISSUE TITLE
Fix potential bug in theoryforge

### ISSUE THREAD

**Issue by mgerbino** [simonsobs/LAT_MFLike#42]
Include cls=self.requested_cls in [call to rot ](https://github.com/simonsobs/LAT_MFLike/blob/7c038a4428699f0b0f9a3ca91d8942d553e7e767/mflike/theoryforge_MFLike.py#L412) and remove it from initialization of Rotation_alm (one line above). 

Note, current implementation does not result in a bug, because, in [syslib](https://github.com/simonsobs/syslibrary/blob/47fe441138342b859554eb7a5fb05c877329c4c8/syslibrary/syslib_mflike.py#L66): i) an additional unused key in Rotation_alm is just redundant; ii) requested_cls only include teee polarization spectra, which are rotated by default by Rotation_alm. 

A bug would be introduced if requested_cls also included bb and/or eb and/or tb.

**Comment by sgiardie** [comment]
Hi @mgerbino, I have fixed the bug as you suggested. It is more linear now, even though the code would have worked also in the old configuration, i.e. the [`set_defaults`](https://github.com/simonsobs/syslibrary/blob/47fe441138342b859554eb7a5fb05c877329c4c8/syslibrary/syslib.py#L57) in the class `result` would have already set `cls=self.requested_cls` as an argument of [`Rotation_alm`](https://github.com/simonsobs/syslibrary/blob/47fe441138342b859554eb7a5fb05c877329c4c8/syslibrary/syslib_mflike.py#L66).
Maybe it is better to have some changes in `Rotation_alm` in order to avoid potential errors: it would be better to substitute the argument `cls=['tt']` with `cls=['tt','ee','te']` and to add before line [82](https://github.com/simonsobs/syslibrary/blob/47fe441138342b859554eb7a5fb05c877329c4c8/syslibrary/syslib_mflike.py#L82) a check that `cls` has `'ee','te'` as fields.
